repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--ds", "--profile", "black", "--filter-files"]
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3