repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--ds", "--profile", "black", "--filter-files"]
  - repo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3